import express from 'express';
const router = express.Router();
import { trackerController } from '@/controllers';
import auth from '@/middlewares/auth';
import { trackerValidation } from '@/validations';
import validate from '@/middlewares/validate';
router.use(auth());
router.get('/get-links', validate(trackerValidation.getLinks), trackerController.getLinks);
router.post('/add-link', validate(trackerValidation.addLink), trackerController.addLink);
export default router;
